# Generated by Django 3.2.5 on 2021-08-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210720_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='disc_bag',
        ),
    ]
