# Generated by Django 3.2.5 on 2021-07-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0002_auto_20210710_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='plastic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
