# Generated by Django 3.2.5 on 2021-08-02 01:19

import discs.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0004_auto_20210713_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disc',
            name='cert_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disc',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='disc',
            name='diameter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disc',
            name='disc_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='disc',
            name='final_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disc',
            name='flexibility',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disc',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disc',
            name='inside_rim_diameter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disc',
            name='rim_configuration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disc',
            name='rim_depth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disc',
            name='rim_depth_to_diameter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disc',
            name='rim_thickness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disc',
            name='vintage_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='img_alt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='img_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='disc',
            name='weight',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MaxValueValidator(500.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='established',
            field=models.IntegerField(blank=True, default=2021, null=True, validators=[discs.models.max_year_validator, django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
