# Generated by Django 3.2.5 on 2021-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0008_auto_20210802_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='type',
            field=models.CharField(choices=[('dist_dr', 'Distance Driver'), ('frwy_dr', 'Fairway Driver'), ('mid_rng', 'Mid-Range '), ('putt', 'Putt/Approach'), ('special', 'Specialty')], default='putt', max_length=15),
        ),
    ]
