# Generated by Django 3.2.5 on 2021-08-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0010_userdisc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdisc',
            old_name='user',
            new_name='profile',
        ),
    ]
