# Generated by Django 3.2.5 on 2021-07-13 03:10

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('country', models.CharField(max_length=75)),
                ('zip_code', models.CharField(max_length=15)),
                ('avg_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_alt', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('par', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tee_box', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('basket', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('avg_score', models.IntegerField(default=0)),
                ('heading', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'ordering': ['hole_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='hole',
            constraint=models.UniqueConstraint(fields=('hole_number', 'course'), name='unique_hole_num'),
        ),
    ]
