# Generated by Django 3.2.5 on 2021-07-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdga_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
