# Generated by Django 3.2.5 on 2021-07-13 21:31

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discs', '0003_disc_plastic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('isInProgress', models.BooleanField(default=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='HoleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('hole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.hole')),
            ],
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('throw', models.CharField(max_length=30)),
                ('dist', models.FloatField()),
                ('isHole', models.BooleanField(default=False)),
                ('disc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discs.disc')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strokes', to='games.holescore')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecards', to='games.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='holescore',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.scorecard'),
        ),
    ]
