# Generated by Django 3.2.5 on 2021-07-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stroke',
            old_name='hole',
            new_name='hole_score',
        ),
    ]
