# Generated by Django 3.2.5 on 2021-07-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_hole_stroke_hole_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='scorecard',
            options={'get_latest_by': '-game__date', 'ordering': ('-id',)},
        ),
    ]
