# Generated by Django 3.2.5 on 2021-08-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0010_userdisc'),
        ('games', '0003_auto_20210720_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroke',
            name='disc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discs.userdisc'),
        ),
    ]
